### ISSUE TITLE
Missing CSS? 

### ISSUE THREAD

**Issue by kamoteshake** [idiotWu/react-smooth-scrollbar#15]
Hi there,

I got this module working it scrolls and what not but I you can't see the scrollbar. It says on the doc to add the styles. I checked the files and I don't see any styles in there. Where can I get the style? do I have to install the smooth-scrollbar along side this module?

**Comment by dolphin-wood** [comment]
Oh sorry, it's a mistake in the document 😅. You can fix it with:

```js
import 'smooth-scrollbar/dist/smooth-scrollbar.css';
```

**Comment by kamoteshake** [comment]
so I do have to install the smooth-scrollbar along side the react-smooth-scrollbar. another question. is there a way to disable vertical or horizontal scroll?

**Comment by dolphin-wood** [comment]
> I do have to install the smooth-scrollbar along side the react-smooth-scrollbar.

I don't think it's necessary to install smooth-scrollbar manually since it is required in package.json: https://github.com/idiotWu/react-smooth-scrollbar/blob/39bc309d1a0e9183aff5f78d7b4d1ed6d6aea085/package.json#L42-L44

> is there a way to disable vertical or horizontal scroll?

No, currently no. But it will come in the next major version (see idiotWu/smooth-scrollbar#84), though I might  not have time to do this until I finish my college entrance exams 😅.

Sorry for the inconvenience.

**Comment by kamoteshake** [comment]
no worries. this is the only scrollbar library that works. LOL. I bet I could create a workaround to disable something. Thanks!

**Comment by kamoteshake** [comment]
For the people who are looking for a way to disable either vertical or horizontal scroll, I did a crappy workaround. 

here's a simplified version of my code. Hopefully this helps.

```javascript
import React, { Component } from 'react';
import Scrollbar from 'react-smooth-scrollbar';
import 'smooth-scrollbar/dist/smooth-scrollbar.css';

class SomeComponent extends Component {
  constructor(props) {
    super(props);
    this.onScroll = this.onScroll.bind(this);
  }

  onScroll(status, data) {
    const { scrollbar } = this.scrollbarInstance;

    // for disabling vertical scroll
    if (status.direction.y !== 'none') {
      scrollbar.setPosition(data.offset.x, 0);
    }

    // for disabling horizontal scroll
    if (status.direction.x !== 'none') {
      scrollbar.setPosition(0, data.offset.y);
    }
  }

  render() {
    return (
      <Scrollbar ref={(dom) => (this.scrollbarInstance = dom)} onScroll={(status, scrollbar) => this.onScroll(status, scrollbar)})>
        <div>Some Content</div>
      </Scrollbar>
    );
  }
}

export default SomeComponent;

**Comment by dolphin-wood** [comment]
Hey @kamoteshake, v8 is out now!

#### How to update

```shell
npm install react-smooth-scrollbar smooth-scrollbar --save
``` 

- [Migration Guide](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/migration.md)
- [API Documentation](https://github.com/idiotWu/smooth-scrollbar/tree/develop/docs)

After updated to v8, you don't need to import the css file any more because it's bundled with js. Meanwhile, your issue of disable scrolling on particular direction could be resolved via the new plugin system:

```js
import { Component } from 'react';
import Scrollbar from 'react-smooth-scrollbar';
import SmoothScrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';

class DisableScrollPlugin extends ScrollbarPlugin {
  static pluginName = 'disableScroll';

  static defaultOptions = {
    direction: null,
  };

  transformDelta(delta) {
    if (this.options.direction) {
      delta[this.options.direction] = 0;
    }

    return { ...delta };
  }
}

SmoothScrollbar.use(DisableScrollPlugin);

class SomeComponent extends Component {
  render() {
    return (
      <Scrollbar plugins={{
        disableScroll: { direction: 'x' }
      }}>
        ...
      </Scrollbar>
    );
  }
}
```

Since I didn't have much time to code, the 8.x version of `react-smooth-scrollbar` is still using the old architecture, old workflow and the old version of react. I'm not sure if it could work well with the latest version of react. I'd suggest you create your own `smooth-scrollbar` wrap in your react projects 😅. The kernel of `react-smooth-scrollbar` is quite simple:  https://github.com/idiotWu/react-smooth-scrollbar/blob/c170baf6bd0d45ec53280a41f9e2d7ebfcbb4560/src/react-smooth-scrollbar.js#L40-L41

**Comment by kamoteshake** [comment]
@idiotWu OMG! Thanks for the update! This is awesome! and thanks for the tips.
